{{- if and (not .Values.config.database.auth.existingSecret) (not .Values.mariadb.enabled) (not .Values.mysql.enabled) (not .Values.postgresql.enabled) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shlink-backend.database.auth.secretName" . }}
data:
  {{- include "shlink-backend.database.auth.secretKey" . | nindent 2 }}: {{ .Values.config.database.auth.password | b64enc }}
{{- end }}
