{{- if not .Values.github.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
  name: {{ include "github-exporter.auth.secretName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.github.auth.app.enabled }}
  github-app-id: {{ .Values.github.auth.app.id | b64enc | quote }}
  github-app-installation-id: {{ .Values.github.auth.app.installationId | b64enc | quote }}
  github-app-private-key: {{ .Values.github.auth.app.privateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.github.auth.token.enabled }}
  github-token: {{ .Values.github.auth.token.value | b64enc | quote }}
  {{- end }}
{{- end }}
