---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
  name: {{ include "github-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
  selector:
    {{- include "github-exporter.selectorLabels" . | nindent 4 }}
