apiVersion: v2
name: tenant-namespace
description: A Helm Chart to bootstrap a Namespace in a Multi-Tenancy setup
version: 2.0.5
type: application
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/tenant-namespace/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: url of icon
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
