{{- if and (.Values.config.matomo.enabled) (not .Values.config.matomo.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shlink-backend.matomo.auth.secretName" . }}
data:
  api-token: {{ .Values.config.matomo.auth.apiToken | b64enc }}
{{- end }}
