{{- if and (include "shlink-backend.matomo.enabled" .) (not .Values.config.matomo.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "shlink-backend.labels" . | nindent 4 }}
  name: {{ include "shlink-backend.matomo.auth.secretName" . }}
data:
  api-token: {{ .Values.config.matomo.auth.apiToken | b64enc }}
{{- end }}
