{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "shlink-backend.labels" . | nindent 4 }}
  name: {{ include "shlink-backend.serviceAccountName" . }}
{{- end }}
