{{- if or .Values.ingress.basicAuth.enabled .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kubevirt-manager.labels" . | nindent 4 }}
  name: {{ template "kubevirt-manager.fullname" . }}
data:
  {{- if .Values.ingress.basicAuth.enabled }}
  basicauth.conf: |
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/secret.d/.htpasswd;
  {{- end }}
  {{- if .Values.prometheus.enabled }}
  prometheus.conf: |
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization "";
        proxy_pass_request_body on;
        proxy_pass_request_headers on;
       	client_max_body_size 5g;
       	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://{{ .Values.prometheus.service.name }}.{{ .Values.prometheus.service.namespace }}.svc:{{ .Values.prometheus.service.port }};
    }
  {{- end }}
{{- end }}
