{{- if and .Values.ingress.basicAuth.enabled (not .Values.ingress.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "kubevirt-manager.labels" . | nindent 4 }}
  name: {{ include "kubevirt-manager.ingress.basicAuth.secretName" . }}
stringData:
  .htpasswd: {{ .Values.ingress.basicAuth.username }}:{{ .Values.ingress.basicAuth.password }}
{{- end }}
