apiVersion: v2
name: proxyweb
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "latest"
home: https://github.com/christianhuth/helm-charts
maintainers: []
sources:
  - https://github.com/edmodo/proxyweb/
deprecated: true
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: URL and name of Helm repository
