{{- if and (not .Values.mariadb.enabled) (not .Values.squest.config.database.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "squest.labels" . | nindent 4 }}
  name: {{ include "squest.database.auth.secretName" . }}
data:
  mariadb-password: {{ .Values.squest.config.database.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.squest.config.database.auth.rootPassword | b64enc }}
{{- end }}
