- id: helm-dependency-update
  name: Update Helm Dependency for changed Charts
  entry: bash -c 'ct list-changed | xargs -d '\n' -I {} helm dependency update {}'
  language: system
  pass_filenames: false

- id: helm-kubeconform
  name: Execute kubeconform for changed Charts
  entry: bash -c 'ct list-changed | xargs -d '\n' -I {} helm kubeconform {}'
  language: system
  pass_filenames: false
