{{- if or (and (.Values.config.mailcow.auth.apiKey) (not .Values.config.mailcow.auth.existingSecret)) (and (.Values.config.exporter.auth.securityToken) (not .Values.config.exporter.auth.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailcow-exporter.exporter.auth.secretName" . }}
data:
  {{- if .Values.config.exporter.auth.securityToken }}
  mailcow-security-token: {{ .Values.config.exporter.auth.securityToken | b64enc }}
  {{- else if .Values.config.mailcow.auth.apiKey }}
  mailcow-security-token: {{ .Values.config.mailcow.auth.apiKey | b64enc }}
  {{- end }}
{{- end }}
