{{- if and .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "mailcow-exporter.fullname" . }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "mailcow-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      {{- if (eq (include "mailcow-exporter.exporter.auth.enabled" .) "0") }}
      params:
        {{- if .Values.config.exporter.auth.securityToken }}
        token:
          - {{ .Values.config.exporter.auth.securityToken | quote }}
        {{- else if .Values.config.mailcow.auth.apiKey }}
        token:
          - {{ .Values.config.mailcow.auth.apiKey | quote }}
        {{- end }}
      {{- end }}
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      path: /metrics
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "mailcow-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
