apiVersion: v2
name: popeye
description: Popeye - A Kubernetes Cluster Sanitizer
type: application
version: 2.1.0
appVersion: "v0.21.3"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_logo.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/derailed/popeye
annotations:
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - kind: changed
      description: bumped image version to 0.21.3
  artifacthub.io/screenshots: |
    - title: Popeye is a utility that scans live Kubernetes cluster and reports potential issues with deployed resources and configurations.
      url: https://popeyecli.io/assets/d_score.png
