apiVersion: v2
name: etcd-defrag
description: A Helm chart for running a defragmentation CronJob for ETCD
type: application
version: 1.1.1
appVersion: "3.5.15"
home: https://github.com/christianhuth/helm-charts
icon: https://cdn.worldvectorlogo.com/logos/etcd-1.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/etcd
  - https://etcd.io
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bumped image version to 3.5.15
