{{ if (not (index .Values "syncstorage" "tokenserver-db" "auth" "existingSecret")) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "syncstorage-rs.labels" . | nindent 4 }}
  name: {{ include "syncstorage-rs.tokenserver-db.auth.secretName" . }}
data:
  database-password: {{ (include "syncstorage-rs.tokenserver-db.auth.password" .) | b64enc }}
  database-url: {{ (include "syncstorage-rs.tokenserver-db.url" .) | b64enc }}
{{- end }}
