---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "squest.celery.beat.labels" . | nindent 4 }}
  name: {{ include "squest.celery.beat.fullname" . }}
spec:
  type: {{ .Values.celery.beat.service.type }}
  ports:
    - port: {{ .Values.celery.beat.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "squest.celery.beat.selectorLabels" . | nindent 4 }}
