{{- if .Values.celery.beat.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.celery.beat.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "squest.celery.beat.labels" . | nindent 4 }}
  name: {{ include "squest.celery.beat.serviceAccountName" . }}
{{- end }}
