{{- if and (.Values.config.mailcow.auth.apiKey) (not .Values.config.mailcow.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailcow-exporter.mailcow.auth.secretName" . }}
data:
  mailcow-api-key: {{ .Values.config.mailcow.auth.apiKey | b64enc }}
{{- end }}
