---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "squest.squest.labels" . | nindent 4 }}
  name: {{ include "squest.squest.fullname" . }}-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
