{{- if .Values.squest.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.squest.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "squest.squest.labels" . | nindent 4 }}
  name: {{ include "squest.squest.serviceAccountName" . }}
{{- end }}
