apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syncserver.fullname" . }}
  labels:
    {{- include "syncserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "syncserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syncserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syncserver.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTPS_METHOD
              value: "noredirect"
            - name: PORT
              value: "5000"
            - name: SYNCSERVER_ALLOW_NEW_USER
              value: {{ .Values.syncserver.config.allowNewUser | quote }}
            - name: SYNCSERVER_BATCH_UPLOAD_ENABLED
              value: {{ .Values.syncserver.config.batchUploadEnabled | quote }}
            - name: SYNCSERVER_DEBUG_ENABLED
              value: {{ .Values.syncserver.config.debugEnabled | quote }}
            - name: SYNCSERVER_FORCE_WSGI_ENVIRON
              value: {{ .Values.syncserver.config.forceWsgiEnviron | quote }}
            - name: SYNCSERVER_PUBLIC_URL
              value: {{ .Values.syncserver.config.publicUrl | quote }}
            - name: SYNCSERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "syncserver.secretName" . }}
                  key: syncserver-secret
            - name: SYNCSERVER_SQLURI
              value: {{ .Values.syncserver.config.sqlUri }}
            {{- range .Values.syncserver.extraEnv }}
            {{- if and (.name) (.value) }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.syncserver.persistence.enabled }}
          volumeMounts:
          - name: data
            mountPath: /data
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.syncserver.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "syncserver.pvcName" . }}
      {{- end }}
