{{ if and (not .Values.syncstorage.masterKey.existingSecret) (.Values.syncstorage.masterKey.value) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "syncstorage-rs.labels" . | nindent 4 }}
  name: {{ include "syncstorage-rs.masterKey.secretName" . }}
data:
  {{- include "syncstorage-rs.masterKey.secretKey" . | nindent 2 }}: {{ .Values.syncstorage.masterKey.value | b64enc }}
{{- end }}
