apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "syncstorage-rs.labels" . | nindent 4 }}
  name: {{ include "syncstorage-rs.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "syncstorage-rs.selectorLabels" . | nindent 4 }}
