{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "countly.frontend.labels" . | nindent 4 }}
  name: {{ include "countly.frontend.serviceAccountName" . }}
{{- end }}
