{{- if not .Values.config.nextcloud.auth.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-exporter.nextcloud.auth.secretName" . }}
data:
  {{- if (eq .Values.config.nextcloud.auth.type "token") }}
  nextcloud-token: {{ .Values.config.nextcloud.auth.token | b64enc }}
  {{- end }}
  {{- if (eq .Values.config.nextcloud.auth.type "basic") }}
  nextcloud-password: {{ .Values.config.nextcloud.auth.password | b64enc }}
  nextcloud-username: {{ .Values.config.nextcloud.auth.username | b64enc }}
  {{- end }}
{{- end }}
