{{- if and (.Values.squest.config.smtp.password) (not .Values.squest.config.smtp.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "squest.squest.labels" . | nindent 4 }}
  name: {{ include "squest.squest.smtp.secretName" . }}
data:
  smtp-password: {{ .Values.squest.config.smtp.auth.password | b64enc }}
{{- end }}
