{{- if and (not .Values.rabbitmq.enabled) (.Values.config.rabbitmq.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "shlink-backend.labels" . | nindent 4 }}
  name: {{ include "shlink-backend.rabbitmq.auth.secretName" . }}
data:
  rabbitmq-password: {{ .Values.config.rabbitmq.auth.password | b64enc }}
{{- end }}
