{{- if and (.Values.config.api.mail.enabled) (not .Values.config.api.mail.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "countly.api.mail.secretName" . }}
data:
  mail-password: {{ .Values.config.api.mail.auth.password | b64enc }}
{{- end }}
