{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "countly.api.labels" . | nindent 4 }}
  name: {{ include "countly.api.serviceAccountName" . }}
{{- end }}
