---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "squest.celery.worker.labels" . | nindent 4 }}
  name: {{ include "squest.celery.worker.fullname" . }}
spec:
  replicas: {{ .Values.celery.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "squest.celery.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "squest.celery.worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: celery-worker
          image: "{{ .Values.celery.worker.image.registry }}/{{ .Values.celery.worker.image.repository }}:{{ .Values.celery.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.celery.worker.image.pullPolicy }}
          command: ['/bin/bash', '-c']
          args:
            - |
              echo "Wait for required services to start"
              /wait
              echo "Starting celery worker"
              celery -A service_catalog worker -l info
          env:
            # Django Settings
            - name: ALLOWED_HOSTS
              value: "*"
            - name: CSRF_TRUSTED_ORIGINS
              value: "*"
            - name: DEBUG
              value: {{ .Values.celery.worker.config.django.debug | quote }}
            - name: GUNICORN_WORKERS
              value: {{ .Values.celery.worker.config.django.gunicornWorkers | quote }}

            # MariaDB Settings
            - name: DB_DATABASE
              value: {{ include "squest.mariadb.auth.database" . | quote }}
            - name: DB_HOST
              value: {{ include "squest.mariadb.host" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "squest.mariadb.auth.secretName" . | quote }}
                  key: mariadb-password
            - name: DB_PORT
              value: {{ include "squest.mariadb.port" . | quote }}
            - name: DB_USER
              value: {{ include "squest.mariadb.auth.username" . | quote }}

            # RabbitMQ Settings
            - name: CELERY_BROKER_URL
              value: {{ (include "squest.rabbitmq.url" .) | quote }}

            # Redis Settings
            - name: REDIS_CACHE_HOST
              value: {{ include "squest.redis.host" . | quote }}
            - name: REDIS_CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "squest.redis.auth.secretName" . }}
                  key: redis-password
            - name: REDIS_CACHE_PORT
              value: {{ include "squest.redis.port" . | quote }}
            - name: REDIS_CACHE_USER
              value: {{ include "squest.redis.auth.username" . | quote }}

            # Wait Settings
            - name: WAIT_HOSTS
              value: {{ include "squest.mariadb.host" . }}:{{ include "squest.mariadb.port" . }},{{ include "squest.rabbitmq.host" . }}:{{ include "squest.rabbitmq.port" . }},{{ include "squest.redis.host" . }}:{{ include "squest.redis.port" . }},{{ include "squest.squest.fullname" . }}:{{ .Values.squest.service.port }}
            - name: WAIT_TIMEOUT
              value: "60"
          {{- if .Values.celery.worker.extraVolumeMounts }}
          volumeMounts:
            {{- with .Values.celery.worker.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "squest.celery.worker.serviceAccountName" . }}
      {{- if .Values.celery.worker.extraVolumes }}
      volumes:
      {{- with .Values.celery.worker.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
