{{- if .Values.celery.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.celery.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "squest.celery.worker.labels" . | nindent 4 }}
  name: {{ include "squest.celery.worker.serviceAccountName" . }}
{{- end }}
