{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.selfMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "dns-exporter.fullname" . }}
  {{- with .Values.serviceMonitor.selfMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "dns-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.selfMonitor.selector }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceMonitor.selfMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      {{- with .Values.serviceMonitor.selfMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      path: /metrics
      {{- with .Values.serviceMonitor.selfMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.selfMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "dns-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
