apiVersion: v2
name: sloop
description: Kubernetes History Visualization
type: application
version: 0.1.0
appVersion: "sha-2ce8bbe"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/sloop/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/salesforce/sloop
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: option to define the image registry
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/screenshots: |
    - title: Visualize the different Events inside your Kubernetes cluster.
      url: https://civo-com-assets.ams3.digitaloceanspaces.com/content_images/989.blog.png
    - title: You can filter the events that should be visualized.
      url: https://raw.githubusercontent.com/milindchawre/civo-k8s/master/blog/sloop/images/sloop1.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
