name: Chart-Preparation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: Install sudo package
        run: apt update && apt install -y sudo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          rootless: true
      - name: Add an exception for dubious ownership check
        run: git config --global --add safe.directory '*'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files || exit 0
      - name: Check for modified files
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Files have been modified by pre-commit."
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changes_detected=false" >> $GITHUB_ENV
          fi
      - name: Commit and push changes
        if: env.changes_detected == 'true'
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Extract the source branch of the PR
            branch_name="${{ github.event.pull_request.head.ref }}"
          else
            # Extract branch from push event
            branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          fi
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout ${{ github.head_ref }}
          git add .
          git commit -m "chore: auto-upgrade schema, readme and changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
