# https://github.com/marketplace/actions/helm-chart-testing
name: Chart-Testing

on:
  pull_request:
    branches: [main]
    paths: ["charts/**"]
  push:
    branches: [main]
    paths: ["charts/**"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Chart-Linting"]
    types: ["completed"]

jobs:

  detect-changed-charts:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.get-changed-charts.outputs.matrix }}
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Identify changed charts
        id: get-changed-charts
        run: |
          CHANGED_CHARTS=$(ct list-changed --config .github/config/chart-testing.yaml | jq --slurp --raw-input 'split("\n")[:-1] | map({chart: .})')
          if [[ -n "$changed-charts" ]]; then
            echo "::set-output name=matrix::$CHANGED_CHARTS"
          fi

      - name: Debug matrix ouput
        run: echo "${{ steps.get-changed-charts.outputs.matrix }}"

  installation:
    needs: detect-changed-charts
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-changed-charts.outputs.matrix) }}
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        run: "ct install --charts ${{ matrix.chart }} --config .github/config/chart-testing.yaml"
