name: Chart-Kubeconform

on:
  workflow_call:
  workflow_dispatch:

jobs:

  kubeconform:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: setup helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: helm dependency update on changed charts
        run : ct list-changed --config .github/config/chart-testing.yaml | xargs -d '\n' -I {} helm dependency update {}

      - name: Set up kubeconform-helm plugin
        run: helm plugin install https://github.com/jtyr/kubeconform-helm

      - name: helm unittest on changed charts
        run : ct list-changed --config .github/config/chart-testing.yaml | xargs -d '\n' -I {} helm kubeconform --verbose --summary {}
