name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Install yq
        uses: dcarbone/install-yq-action@v1

      - name: Install homplate
        run: |
          curl -o /usr/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v4.3.0/gomplate_linux-am64
          chmod 755 /usr/bin/gomplate

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.18
        env:
          LOG_LEVEL: DEBUG  # or INFO, WARN, ERROR, FATAL
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: .github/config/renovate.js
          docker-cmd-file: ./renovate-action-entrypoint.sh
          docker-user: root
          docker-volumes: |
            /usr/bin/gomplate:/usr/local/bin/gomplate ;
            /usr/bin/yq:/usr/local/bin/yq ;
          token: ${{ secrets.RENOVATE_TOKEN }}
