name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.18
        env:
          LOG_LEVEL: DEBUG  # or INFO, WARN, ERROR, FATAL
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: .github/config/renovate.js
          docker-cmd-file: ./renovate-action-entrypoint.sh
          docker-user: root
          docker-volumes: |
            ./github/generate-chart-changelogs.sh:/generate-chart-changelogs.sh
          token: ${{ secrets.RENOVATE_TOKEN }}
