name: Start

on:
  pull_request:
    branches: [main]
    paths: ["charts/**"]
  push:
    branches: [main]
    paths: ["charts/**"]
  workflow_dispatch:

jobs:
  call-prepare:
    uses: ./.github/workflows/prepare.yml
  call-linting:
    uses: ./.github/workflows/chart-linting.yml
  call-testing:
    uses: ./.github/workflows/chart-testing.yml
