{{- if and (include "shlink-backend.mercure.enabled" .) (not .Values.config.mercure.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "shlink-backend.labels" . | nindent 4 }}
  name: {{ include "shlink-backend.mercure.auth.secretName" . }}
data:
  jwt-secret: {{ .Values.config.mercure.auth.jwtSecret | b64enc }}
{{- end }}
