{{- if and (.Values.config.mercure.enabled) (not .Values.config.mercure.auth.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shlink-backend.mercure.auth.secretName" . }}
data:
  jwt-secret: {{ .Values.config.mercure.auth.jwtSecret | b64enc }}
{{- end }}
